filtro do ultrassom
UnbDroid/Trekking2022 pull request #3
Opened 2022-10-22 16:31 UTC by David-Chatelard

Classe com o filtro para o ultrassom e classe de teste para ele.

2022-10-22 21:16 UTC, lschiavini commented on Trekking/src/UltrasonicFilter.cpp
> +    Serial.println();
Melhor concatenar values[i] numa string e só printar no final, até pra fins de teste printar assim vai deixar mais devagar

2022-10-22 21:18 UTC, lschiavini commented on Trekking/include/UltrasonicFilter.h
> +    static const int NUM_OF_SAMPLES = 1; // valor usado para definir quantos valores filtrados serão retornados
Acho q da pra chamar de NUM_OF_SPREAD_INTERVAL_SAMPLES ou NUM_OF_SPREAD_MEDIAN
NUM_MEDIAN_SAMPLES

2022-10-22 21:19 UTC, lschiavini requested changes
Pequenas alteraçoes

2022-10-24 18:58 UTC, David-Chatelard commented on Trekking/src/UltrasonicFilter.cpp
> +    Serial.println();
Fiz a mudança, mas não estou na droid hoje, então não consigo testar. Amanhã eu testo se está funcionando o novo print

2022-10-24 22:21 UTC, lschiavini approved these changes

2022-10-24 22:22 UTC, merged